

		var head = document.querySelector("h5");
		var add = document.querySelector("#add");

		var check = 0;

		add.addEventListener("click", function () {
			if (check == 0) {
				head.innerHTML = "Friends";
				head.style.color = "green";
				add.innerHTML = "Remove Friend";
				check = 1;
			} else {
				head.innerHTML = "Stranger";
				head.style.color = "red";
				add.innerHTML = "Add Friend";

				check = 0;
			}
		})





	