
		var box = document.querySelector("#container");
		var like = document.querySelector("i");


		box.addEventListener("dblclick", () =>{
			like.style.transform = "translate(50% - 50%), scale(1)";
			like.style.opacity = "0.7";

			setTimeout(() => {
				like.style.opacity = "0";
			}, 1000);

			setTimeout(() => {
				love.style.transform =  "translate(50% - 50%), scale(0)";
			}, 3000);

			console.log("hello")
		})

